# Generated by Django 4.0.6 on 2022-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, verbose_name='Коммент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Редактировано')),
                ('is_confirm', models.BooleanField(default=True, verbose_name='Подтверждения!')),
            ],
            options={
                'verbose_name': 'Web-приглосительное',
                'verbose_name_plural': 'Пригласительные',
                'ordering': ['-created_at'],
            },
        ),
    ]
