# Generated by Django 4.0.6 on 2022-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждения!'),
        ),
    ]
